language: python
python:
  - "3.6"
script: pytest tests/
deploy:
  provider: pypi
  user: danggrianto
  password:
    secure: srSFPcqT/ftHwnQewFCclvM58TWpjsWe5VCJp55KpMurDSB/spTAVqhrEIWMs4VtJ91/sIEkZDYPlMaaLi+sO1i2IZP514/pzmT1OaR28YQ8MwfLaDtdowJA4rYKj5RW/0A79NPGP5ZdrMHfhLgqlG0Nvdl5pEqTQjKvD/F6V9K2SsJmo4UgKwEsIPPECBhtMojyFl1KbhohHbsj0COLKaZb6DSY7u/N4mPdh3Omp1rffPC/5zdcaI0IBLtmlryTVhlFDKCbv84ts41ekyEndzEGpcLt1js+b+PxNFeBimyEZUbYHOC2KCqPWXN8WgtT7h4piivUY4aN0mdhkonHXjoN0LU8B/3mgPJr73sAmWhVTpVY5LFnYo7OwcudSCqWs/JfYCEmLc7dxsQgszKcYFtRA7L3YymWvEXAVGc/5nqJMHMeuER4yGL7g4mdgtOubavuAKnwiJrCIr8P2loklwB1EEBXXCHB/dbFrtHSAt3PTqgMA/Lff3ZMsnenbt5ak8eWYo+bCJ5q/W3CxHHnruS4IVT2525w2h5KkViPJlK4pNOrhQwKt7oS62OFZOqPnc8NUVIZh6GNaWeGXbQaFWAMDDc/w6cTaussTMEuLGRwbh6CFR1qa3HgcyzqdfLX1efkiUUErKJvPe+gJ+I6W5kZThcXQHSCA3ix1Vopoqk=
  on:
    tags: true
